"""Initial database schema

Revision ID: ed87fcaaacad
Revises: 
Create Date: 2026-02-05 19:40:30.836765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed87fcaaacad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=16), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('encrypted_pem', sa.Text(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keys_algorithm'), 'keys', ['algorithm'], unique=False)
    op.create_index(op.f('ix_keys_fingerprint'), 'keys', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_keys_id'), 'keys', ['id'], unique=False)
    op.create_index(op.f('ix_keys_is_deleted'), 'keys', ['is_deleted'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=64), nullable=False),
    sa.Column('key_usage', sa.Text(), nullable=False),
    sa.Column('extended_key_usage', sa.Text(), nullable=False),
    sa.Column('policy', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_is_builtin'), 'templates', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_index(op.f('ix_templates_template_type'), 'templates', ['template_type'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ROOT', 'INTERMEDIATE', 'LEAF', name='certificatetype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('subject_cn', sa.String(length=255), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'EXPIRED', name='certificatestatus'), nullable=True),
    sa.Column('certificate_der', sa.LargeBinary(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_is_deleted'), 'certificates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_certificates_key_id'), 'certificates', ['key_id'], unique=False)
    op.create_index(op.f('ix_certificates_not_after'), 'certificates', ['not_after'], unique=False)
    op.create_index(op.f('ix_certificates_not_before'), 'certificates', ['not_before'], unique=False)
    op.create_index(op.f('ix_certificates_parent_id'), 'certificates', ['parent_id'], unique=False)
    op.create_index(op.f('ix_certificates_serial_number'), 'certificates', ['serial_number'], unique=True)
    op.create_index(op.f('ix_certificates_status'), 'certificates', ['status'], unique=False)
    op.create_index(op.f('ix_certificates_subject_cn'), 'certificates', ['subject_cn'], unique=False)
    op.create_index(op.f('ix_certificates_type'), 'certificates', ['type'], unique=False)
    op.create_table('crls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('crl_number', sa.Integer(), nullable=False),
    sa.Column('crl_der', sa.LargeBinary(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crls_ca_id'), 'crls', ['ca_id'], unique=False)
    op.create_index(op.f('ix_crls_crl_number'), 'crls', ['crl_number'], unique=False)
    op.create_index(op.f('ix_crls_generated_at'), 'crls', ['generated_at'], unique=False)
    op.create_index(op.f('ix_crls_id'), 'crls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crls_id'), table_name='crls')
    op.drop_index(op.f('ix_crls_generated_at'), table_name='crls')
    op.drop_index(op.f('ix_crls_crl_number'), table_name='crls')
    op.drop_index(op.f('ix_crls_ca_id'), table_name='crls')
    op.drop_table('crls')
    op.drop_index(op.f('ix_certificates_type'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_subject_cn'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_status'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_serial_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_parent_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_not_before'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_not_after'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_key_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_is_deleted'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_templates_template_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_builtin'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_keys_is_deleted'), table_name='keys')
    op.drop_index(op.f('ix_keys_id'), table_name='keys')
    op.drop_index(op.f('ix_keys_fingerprint'), table_name='keys')
    op.drop_index(op.f('ix_keys_algorithm'), table_name='keys')
    op.drop_table('keys')
    # ### end Alembic commands ###
